import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Home/NavBar";
import Footer from "./Home/Footer";
import TopBar from "./Home/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Why Global sevices",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <NavBar />
        <div className="pt-10">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
