import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Homepage/NavBar";
import Footer from "./Homepage/Footer";
import TopBar from "./Homepage/TopBar";
import whys from '../../public/why global logo small.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Why Global sevices",
  description: "Generated by create next app",
  icons:{
    icon:"/public/smallwgs.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    
  
      <body className={inter.className}>
      <link rel="icon" href="/public/smallwgs.png" sizes="any" />
        <TopBar />
        <NavBar />
        <div className="pt-[66px] sm:pt-[72px] md:pt-[96px]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
